---
title: "International Datathon on Animal Health Organised by the World Organisation for Animal Health (WOAH)"
author: "Data Integration & Analytics Department, WOAH"
date: last-modified
format:
  html:
    embed-resources: false
    toc: true
    number-sections: false
---

Welcome to the WOAH Datathon web page!  

## Overview 

The World Organisation for Animal Health (WOAH) invites multidisciplinary teams to participate in an international datathon on animal health data science, focusing on surveillance, risk, trade and impact assessment.

Participants will work remotely over several months to address real‑world analytical challenges using pilot datasets provided by WOAH and partners. The datathon aims to stimulate innovation, methodological rigor and decision‑relevant analytics in animal health.

The top three winning teams will share 20000€ in prize money, the opportunity to be featured in the Animal Echo and to present their work at a dedicated side event during the WOAH General Session in 2027.

## Who Can Participate

The datathon is open to international, multidisciplinary teams (1–6 members), including but not limited to:

-   Data scientists and statisticians

-   Epidemiologists

-   Economists

-   Computer scientists

-   Public health and animal health professionals

Teams may include members from academia (students or faculty), public institutions, international organisations, NGOs or the private sector.

## Timeline

-   Official launch: March 2026
-   Deadline for registration: May 31th 2026
-   Team work: Independent and asynchronous (remote participation)
-   Support: Documentation, data descriptions and periodic technical clarifications
- Final submission: analytical pipeline + report on a git repo by **October 31st, 2026.**

## Organisation and Deliverables

Each team will:

-   Select one challenge either from the [list](./challenges.html) or self-proposed (subject to approval)

-   Develop a complete data science pipeline, including data processing, modelling and validation

-   Produce analytical outputs based on pilot or historical datasets

-   Document methods and results in a concise technical report

-   All code must be reproducible and submitted as a git push to a public repository (e.g., GitHub, GitLab) with clear instructions for replication.


## Stay Informed


### Mailing list 

To stay up to date with the latest news regarding  the WOAH Datathon, please register to the 
**[datathon mailing list here.](https://forms.office.com/e/RPa8ZQDSTD)**

### FAQs
For any general question, please check the **[FAQs](./faq.html)** page before contacting us.

### Contact
If needed, write to us through  **dataintegration.dept \@ w o a h . o r g** with subject line **"WOAH Datathon"**


