name: Rebuild TeamUp page   

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'     # Rebuilds once a day at midnight UTC
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  rebuild:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libuv1-dev libssl-dev  

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'

      - name: Install R packages
        run: |
          # Install the 'engine' packages Quarto needs first
          install.packages(c("rmarkdown", "knitr", "curl", "fs","rlang"))
          # Install your project-specific packages
          install.packages(c("googlesheets4", "dplyr", "htmltools", "stringr", "glue"))  
          install.packages(c("dplyr","tidyr","ggplot2","purrr","readxl","patchwork","janitor","countrycode","rnaturalearth","rnaturalearthdata"))
        shell: Rscript {0}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render site
        run: quarto render

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
